version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    env_file: .env
    restart: always
    ports:
      - "3000:3000" # app
      - "5555:5555" # studio
    volumes:
      - .:/viewtasks-backend
      - /viewtasks-backend/node_modules
    depends_on:
      - db

  migrate:
    build:
      context: .
      target: development
    env_file: .env
    command: pnpm db:migrate dev
    volumes:
      - .:/viewtasks-backend
      - /viewtasks-backend/node_modules
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

networks:
  default:
    name: app

volumes:
  db: